import warnings

import numpy as np
import torch
import torchvision.transforms as T
from torchvision.datasets import SVHN

warnings.filterwarnings("ignore", category=UserWarning)

# imagecorruptions targets old numpy/skimage. Restore aliases removed in
# NumPy 2.0 (np.float_) before importing it.
if not hasattr(np, "float_"):
    np.float_ = np.float64

# imagecorruptions calls skimage's gaussian() with the `multichannel` kwarg,
# removed in scikit-image >= 0.21 (now `channel_axis`). Shim it so the package
# keeps working without pinning an old skimage.
import skimage.filters as _skfilters

_orig_gaussian = _skfilters.gaussian


def _gaussian_shim(*args, **kwargs):
    if "multichannel" in kwargs:
        multichannel = kwargs.pop("multichannel")
        kwargs.setdefault("channel_axis", -1 if multichannel else None)
    return _orig_gaussian(*args, **kwargs)


_skfilters.gaussian = _gaussian_shim

import imagecorruptions.corruptions as _ic_corruptions
_ic_corruptions.gaussian = _gaussian_shim

from imagecorruptions import corrupt


def load_svhn_c(
    corruption: str,
    severity: int = 5,
    data_dir: str = "./data",
    indices: list[int] | None = None,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Load SVHN test set, apply corruption, return ``(x, y)``.

    SVHN has no prebuilt corrupted set; SVHN-C is generated by applying the
    CIFAR-10-C corruptions to each SVHN test image.

    :param corruption: corruption name to apply to each image.
    :type corruption: str
    :param severity: corruption severity level (1-5).
    :type severity: int
    :param data_dir: directory the SVHN test set is downloaded to / read from.
    :type data_dir: str
    :param indices: optional subset of test indices to load and corrupt; ``None``
        loads the full test set.
    :type indices: list[int] | None
    :returns: ``(x, y)`` where ``x`` is ``Tensor[N, 3, 32, 32]`` in ``[0, 1]``
        and ``y`` is ``Tensor[N]`` with class labels (0-9).
    :rtype: tuple[torch.Tensor, torch.Tensor]
    """
    dataset = SVHN(root=data_dir, split="test", download=True,
                   transform=T.ToTensor())

    if indices is not None:
        subset = torch.utils.data.Subset(dataset, indices)
    else:
        subset = dataset

    imgs, labels = [], []
    for img_tensor, label in subset:
        img_np = (img_tensor.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
        img_corrupted = corrupt(img_np, corruption_name=corruption, severity=severity)
        imgs.append(torch.from_numpy(img_corrupted).permute(2, 0, 1).float() / 255.0)
        labels.append(label)

    x = torch.stack(imgs)
    y = torch.tensor(labels, dtype=torch.long)
    return x, y
