import warnings
from pathlib import Path

import numpy as np
import torch
import torchvision.transforms as T
from torchvision.datasets import SVHN

warnings.filterwarnings("ignore", category=UserWarning)

# imagecorruptions targets old numpy/skimage. Restore aliases removed in
# NumPy 2.0 (np.float_) before importing it.
if not hasattr(np, "float_"):
    np.float_ = np.float64

# imagecorruptions calls skimage's gaussian() with the `multichannel` kwarg,
# removed in scikit-image >= 0.21 (now `channel_axis`). Shim it so the package
# keeps working without pinning an old skimage.
import skimage.filters as _skfilters

_orig_gaussian = _skfilters.gaussian


def _gaussian_shim(*args, **kwargs):
    """skimage compat: map the removed ``multichannel`` kwarg to ``channel_axis``."""
    if "multichannel" in kwargs:
        multichannel = kwargs.pop("multichannel")
        kwargs.setdefault("channel_axis", -1 if multichannel else None)
    return _orig_gaussian(*args, **kwargs)


_skfilters.gaussian = _gaussian_shim

import imagecorruptions.corruptions as _ic_corruptions

_ic_corruptions.gaussian = _gaussian_shim

from imagecorruptions import corrupt


def load_svhn_c(
    corruption: str,
    severity: int = 5,
    data_dir: str = "./data",
    indices: list[int] | None = None,
    seed: int = 0,
    cache: bool = True,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Load SVHN test set, apply corruption, return ``(x, y)``.

    SVHN has no prebuilt corrupted set; SVHN-C is generated by applying the
    CIFAR-10-C corruptions to each SVHN test image. The stochastic corruptions
    draw from the global ``np.random`` state, so the generator is seeded before
    the per-image loop to make ``(corruption, severity, seed)`` reproducible.

    :param corruption: corruption name to apply to each image.
    :type corruption: str
    :param severity: corruption severity level (1-5).
    :type severity: int
    :param data_dir: directory the SVHN test set is downloaded to / read from.
    :type data_dir: str
    :param indices: optional subset of test indices to load and corrupt; ``None``
        loads the full test set.
    :type indices: list[int] | None
    :param seed: seed for ``np.random`` applied before the per-image corruption
        loop; the same ``(corruption, severity, seed)`` yields identical images.
    :type seed: int
    :param cache: when ``True``, read/write a full-set ``uint8`` cache at
        ``{data_dir}/svhnc_cache/{corruption}_s{severity}_seed{seed}.npz`` (a
        cache hit needs no SVHN dataset / download); when ``False``, generate
        only ``indices`` with no disk cache.
    :type cache: bool
    :returns: ``(x, y)`` where ``x`` is ``Tensor[N, 3, 32, 32]`` in ``[0, 1]``
        and ``y`` is ``Tensor[N]`` with class labels (0-9).
    :rtype: tuple[torch.Tensor, torch.Tensor]
    """

    def _corrupt_all(items):
        """Corrupt every ``(img, label)`` pair -> ``(uint8 [N,3,32,32], int64 [N])``."""
        np.random.seed(seed)  # deterministic stochastic corruptions
        xs, ys = [], []
        for img_t, lab in items:
            a = (img_t.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
            c = corrupt(a, corruption_name=corruption, severity=severity)
            xs.append(np.transpose(c, (2, 0, 1)))
            ys.append(int(lab))
        return np.stack(xs).astype(np.uint8), np.asarray(ys, dtype=np.int64)

    if cache:
        cdir = Path(data_dir) / "svhnc_cache"
        cpath = cdir / f"{corruption}_s{severity}_seed{seed}.npz"
        if cpath.exists():
            blob = np.load(cpath)
            xf, yf = blob["x"], blob["y"]
        else:
            ds = SVHN(
                root=data_dir, split="test", download=True, transform=T.ToTensor()
            )
            xf, yf = _corrupt_all(ds)
            cdir.mkdir(parents=True, exist_ok=True)
            np.savez(cpath, x=xf, y=yf)
        x = torch.from_numpy(xf).float() / 255.0
        y = torch.from_numpy(yf).long()
        if indices is not None:
            x, y = x[indices], y[indices]
        return x, y

    ds = SVHN(root=data_dir, split="test", download=True, transform=T.ToTensor())
    sel = ds if indices is None else torch.utils.data.Subset(ds, indices)
    xf, yf = _corrupt_all(sel)
    return torch.from_numpy(xf).float() / 255.0, torch.from_numpy(yf).long()
